Feat: [#129] 검색 페이지 동행 구인글 및 공연글 필터링 목록 조회 api 연결
GoGo-Ring/dongoorami-frontend pull request #140
Opened 2024-03-15 14:54 UTC by yeon-kk

## 📝 작업 내용

1. 공연과 구인을 호출하는 `useInfiniteQuery`를 각각 hook으로 분리했습니다.
2. `더보기` 버튼을 클릭시 무한스크롤이 시작됩니다. `더보기` 버튼은 무한스크롤이 시작되면 사라지게 됩니다.
3. 검색 조건 변경시, 버튼 및 리스트 개수가 초기 상태로 보여집니다.
4. `useIntersectionObserver`: intersectionObserver를 hook으로 분리했습니다. 
    - [props] `handleFetchNextPage` `hasNextPage`
    - fetchNextPage를 호출하는 핸들러 함수를 prop으로 전달받습니다. (무한스크롤에서 반환하는 fetchNextPage 함수입니다.)
    - 무한스크롤에서 반환하는 hasNextPage를 prop으로 전달받습니다. 관찰 대상이 뷰에 나타나고, hasNextPage가 true이면 핸들러 함수를 호출합니다.
    - useIntersectionObserver는 HTMLDivElement타입의 `ref`를 반환합니다. 사용하려는 곳에서 리스트의 마지막 요소 div에 ref를 전달하면, 대상 관찰 요소로 지정됩니다.
6. useInfiniteAccompanies와 useInfinitePerformances
    - `params`를 매개변수로 받습니다. `검색 조건`에 따라 `url`이 변경되었을 때, params로 인해 호출되는 내용이 변경 됩니다.
    - `queryKey`에 params를 추가했습니다. 문자열 하나로 key를 설정하면 여러개의 key를 사용하는 것 보다 각 연산에 들어가는 시간이 상대적으로 적을 것이라 생각되었습니다.
    - 백엔드 API 명세서에 hasNext가 포함되어 있어서 이를 사용했습니다. hasNext가 true이면 다음 페이지를 호출할 수 있습니다.

- close #129

## 📷 스크린샷 (선택)

## 💬 리뷰 요구사항(선택)

2024-03-16 15:28 UTC, ienrum commented on app/search/_component/companion-recruitment-list.tsx
> +                status={status}
이부분도 
```suggestion
            ({
              id,
              createdAt,
              ...rest
            }) => (
              <CompanionRecruitmentCard
                key={id}
                id={id}
                createdAt={new Date(createdAt)}
                {...rest}
```

이렇게 바꿀수도있을까요?!

2024-03-16 15:29 UTC, ienrum commented on app/search/_component/companion-recruitment-list.tsx
> +        {isInfinite && <div ref={ref} />}
오호 그냥 이렇게 쓰면 되는군요!! 감사합니다. 참조해서 써보겠습니다👍👍

2024-03-16 15:30 UTC, ienrum commented on app/search/_component/useIntersectionObserver.ts
> +const useIntersectionObsever = ({
👍👍

2024-03-16 15:38 UTC, ienrum reviewed
연경님! 수고하셨습니다!
main merge 하셔서
커밋하시면서, ts 에러 잡아보셔야할것 같아요!😭

2024-03-16 15:41 UTC, yeon-kk commented
@ienrum 감사합니다 수혁님! msw 코드를 아직 push하지 않아서, 수정하고 다시 확인하겠습니다. 감사합니다~!

2024-03-18 11:09 UTC, ienrum requested changes
수고하셨습니다!! 연경님!👍

2024-03-18 11:09 UTC, ienrum commented on app/search/_component/performance-info-card.tsx
> +      <Link href={`${BASE_URL}/performance/${id}`}>
BASE_URL 은 api 보낼때의 url 같은데 혹시 의도하신걸까요??🧐

2024-03-18 11:09 UTC, ienrum commented on app/search/_component/performance-info-list.tsx
> +                status={status as StatusType}
여기도 data.page.perfromaceList 에 해당하는 타입에 미리 satus 를 StatusType 으로 지정해놓으면 as 를 붙이지지않아도 될것같아요!!

2024-03-18 11:09 UTC, ienrum commented on hooks/infinite/useInfiniteAccompanies.ts
> +    queryFn: async ({ pageParam }): Promise<AccompanyPostInfoList> => {
```suggestion
    queryFn: ({ pageParam }) => {
```
타입 지정 없이도 똑같이 추론되는것 같아요!!

2024-03-18 11:09 UTC, ienrum commented on hooks/infinite/useInfinitePerformances.ts
> +    queryFn: async ({ pageParam }): Promise<PerformanceList> => {
```suggestion
    queryFn: ({ pageParam }) => {
```

2024-03-18 11:12 UTC, ienrum approved these changes

2024-03-19 01:43 UTC, yeon-kk commented on apis/scheme/performance.ts
> +}
넵! status만 타입에서 차이가 있습니다. 공통인 부분을 따로 분리해보겠습니다. 👍

2024-03-19 01:44 UTC, yeon-kk commented on apis/scheme/accompany.ts
> +}
넵 수정하겠습니다~!

2024-03-19 01:56 UTC, seongminn reviewed
고생하셨습니다 연경님!!

2024-03-19 01:56 UTC, seongminn commented on apis/companion.ts
> +    url: `/accompanies/posts?${params}&size=${pageParam}${cursorId}`,
axios options의 params를 이용해보는 것은 어떨까요? 훨씬 가독성 있게 작성할 수 있을 거 같아요!

[참고자료](https://axios-http.com/docs/req_config)

2024-03-19 01:56 UTC, seongminn commented on app/search/_component/filter-search.tsx
> +  };
이 함수들을 다시 한 번 래핑하신 이유가 있을까요?!

2024-03-19 01:56 UTC, seongminn commented on app/search/_component/useIntersectionObserver.ts
> +  return [ref];
P5: 하나만 내려보내 주고 있다면 `return ref` 와 `return [ref]`가 크게 다르지 않을 것 같군요ㅎㅎ 아니면 `return { ref }` 같은 방법으로 이름을 정해서 내보내주는 방법도 있을 것 같아요ㅎㅎ

2024-03-19 01:56 UTC, seongminn commented on app/search/_component/useIntersectionObserver.ts
> +        { threshold: 0 };
옵션도 넘겨 받을 수 있도록 하면 더 범용적인 훅이 될 것 같아요!

2024-03-19 01:56 UTC, seongminn commented on app/search/_component/useIntersectionObserver.ts
> +  const ref = useRef<HTMLDivElement>(null);
ref를 항상 Div 태그에만 바인딩 하는 것은 아닐 것 같아요! 이 부분은 제네릭으로 처리할 수 있지 않을까 합니다! 일단 작업 시간이 오래 걸릴 것 같으면 지금 당장 해결할 문제는 아닐 것 같네요ㅎㅎ

2024-03-19 01:56 UTC, seongminn commented on app/search/_component/useIntersectionObserver.ts
> +    const { current } = ref;
current가 없을 때 먼저 early return을 해주면 아래에서 불필요하게 IntersectionObserver 인스턴스를 생성하는 과정도 줄일 수 있을 것 같아요!

2024-03-19 01:56 UTC, seongminn commented on hooks/infinite/useInfiniteAccompanies.ts
> +    queryFn: async ({ pageParam }): Promise<AccompanyPostInfoList> => {
덧붙여서 아래와 같이 작성해도 좋을 것 같아요ㅎㅎ
```ts
queryFn: ({ pageParam }) => getCompanionsList(params, SIZE, pageParam)
```

2024-03-19 01:56 UTC, seongminn commented on hooks/infinite/useInfiniteAccompanies.ts
infinite라는 별도의 폴더로 구분해주셨네요! 좋은 시도인 것 같아요ㅎㅎ 다만 무한 스크롤 역시 query 라는 큰 범주에 속하기 때문에 queries에 두고 네이밍으로 useInfiniteAccompaniesFetch 와 같이 표시해주는 방법도 좋을 것 같다는 생각이 들었어요! 이 부분은 지금 크게 중요한 정보는 아닐 것 같네요! 그래서 무시하셔도 좋습니다ㅎㅎ

2024-03-19 01:56 UTC, seongminn commented on app/search/_component/performance-info-card.tsx
>    const height = 288;
width랑 height를 따로 변수화 한 이유가 있을까요?!

2024-03-19 01:59 UTC, yeon-kk commented on app/search/_component/performance-info-card.tsx
> +      <Link href={`${BASE_URL}/performance/${id}`}>
앗!! 감사합니다

2024-03-19 03:47 UTC, yeon-kk commented on apis/companion.ts
> +    url: `/accompanies/posts?${params}&size=${pageParam}${cursorId}`,
직렬화가 필요해서 string으로 변환했었어요~!

와우 근데 문서를 보니까 axios의 paramsSerializer를 같이 사용하면 직렬화가 가능하네요!!! 👍👍👍

변환하는 함수를 같이 수정해야 해서, Refactor 이슈를 따로 만들어서 작업해보겠습니다

2024-03-19 04:12 UTC, yeon-kk commented on app/search/_component/filter-search.tsx
> +  };
컴포넌트 인자로 fetchNextAccompaniesPage를 바로 넘겨준다면 타입이 구체적으로 지정된다고 생각했어요.
그리고 컴포넌트 인자에서 익명함수로 전달하는 경우, 이후 수정이 번거롭거나 코드를 읽기 불편할 것 같았습니다.

2024-03-19 04:48 UTC, yeon-kk commented on hooks/infinite/useInfiniteAccompanies.ts
오호 저는 queries 폴더에 들어가는 Fetch 쿼리 파일들이 점점 늘어난다는 생각이 들었어요. 

그리고 useFetch 형태로 사용되는 useQuery와 다르게, useInfiniteQuery는 pageParam관련 옵션들이 포함되기도 하고 getNextPageParam의 경우 cursorId를 얻기 위해 연산하는 코드가 필요해서 조금 성격이 다른 것 같다고 생각했어요 😄

2024-03-19 04:54 UTC, yeon-kk commented on app/search/_component/performance-info-card.tsx
>    const height = 288;
prop으로 받으면서, 옵셔널로 변경하는 것도 괜찮을 것 같아요. 혹시 질문하신 의도가 맞을까요?

2024-03-19 08:02 UTC, merged